# Generated by Django 5.2 on 2025-05-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('message', models.TextField()),
                ('task_name', models.CharField(max_length=255)),
                ('traceback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('image_link', models.URLField()),
                ('availability', models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('preorder', 'Preorder')], max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('gtin', models.CharField(max_length=100)),
                ('additional_image_links', models.JSONField(blank=True, null=True)),
                ('shipping', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=50, null=True)),
                ('item_group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_product_category', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('pattern', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('product_length', models.CharField(blank=True, max_length=50, null=True)),
                ('product_width', models.CharField(blank=True, max_length=50, null=True)),
                ('product_height', models.CharField(blank=True, max_length=50, null=True)),
                ('product_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('lifestyle_image_link', models.URLField(blank=True, null=True)),
                ('max_handling_time', models.IntegerField(blank=True, null=True)),
                ('is_bundle', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
