# Generated by Django 5.2 on 2025-05-07 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_availability_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
