# Generated by Django 5.2 on 2025-05-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_importanalytics_options_alter_logs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importanalytics',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
    ]
