# Generated by Django 5.2 on 2025-05-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_importanalytics_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importanalytics',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=100),
        ),
    ]
